---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: Cloud Volumes ONTAP システム上で Write Once Read Many （ WORM ）ストレージをアクティブにして、指定した保存期間内にファイルを変更せずに保持できます。クラウド WORM ストレージには SnapLock テクノロジが採用されており、 WORM ファイルはファイルレベルで保護されます。 
---
= WORM ストレージ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP システム上で Write Once Read Many （ WORM ）ストレージをアクティブにして、指定した保存期間内にファイルを変更せずに保持できます。クラウド WORM ストレージには SnapLock テクノロジが採用されており、 WORM ファイルはファイルレベルで保護されます。

WORM機能は、お客様所有のライセンスを使用（BYOL）およびマーケットプレイスのサブスクリプションと組み合わせて使用できます。追加コストはかかりません。NetAppの営業担当者に連絡して、現在のライセンスにWORMを追加してください。



== WORM ストレージの仕組み

WORM ストレージにコミットされたファイルは、保持期間が過ぎたあとも変更することはできません。改ざん防止クロックは、 WORM ファイルの保持期間が経過したタイミングを決定します。

保存期間が経過すると、不要になったファイルを削除する必要があります。



== WORM ストレージのアクティブ化

WORMストレージをアクティブ化する方法は、使用しているCloud Volumes ONTAP のバージョンによって異なります。



=== バージョン9.10.1以降

Cloud Volumes ONTAP 9.10.1以降では、WORMをボリュームレベルで有効または無効にすることができます。

新しいCloud Volumes ONTAP 作業環境を作成する場合は、WORMストレージを有効または無効にするように求められます。

* 作業環境の作成時にWORMストレージを有効にすると、BlueXPで作成したすべてのボリュームでWORMが有効になります。ただし、WORMが無効になっているボリュームは、ONTAP System ManagerまたはONTAP CLIを使用して作成できます。
* 作業環境の作成時にWORMストレージを無効にすると、BlueXP 、ONTAP System Manager、またはONTAP CLIで作成するすべてのボリュームでWORMが無効になります。




=== バージョン9.10.0以前

新しい作業環境を作成するときに、 Cloud Volumes ONTAP システムで WORM ストレージをアクティブにできます。BlueXPで作成するすべてのボリュームでWORMが有効になっています。WORMストレージは個 々 のボリュームで無効にすることはできません。



== ファイルを WORM にコミットしています

アプリケーションを使用して、 NFS または CIFS を介してファイルを WORM にコミットしたり、 ONTAP CLI を使用してファイルを WORM に自動コミットしたりできます。また、追記可能 WORM ファイルを使用して、ログ情報のように増分的に書き込まれるデータを保持することもできます。

Cloud Volumes ONTAP システムで WORM ストレージをアクティブにした後は、 WORM ストレージのすべての管理に ONTAP CLI を使用する必要があります。手順については、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["ONTAP のドキュメント"^]。



== Cloud Volumes ONTAP作業環境でのWORMの有効化

BlueXP  でCloud Volumes ONTAP作業環境を作成するときに、WORMストレージを有効にすることができます。作成時にWORMが有効になっていない場合は、作業環境でWORMを有効にすることもできます。一度有効にすると、WORMを無効にすることはできません。

.このタスクについて
* WORMはONTAP 9 10.1以降でサポートされています。
* バックアップを含むWORMは、ONTAP 9 .11.1以降でサポートされます。


.手順
. [Canvas]ページで、WORMを有効にする作業環境の名前をダブルクリックします。
. [概要]タブで、[機能]パネルをクリックし、* WORM *の横にある鉛筆アイコンをクリックします。
+
システムでWORMがすでに有効になっている場合、鉛筆のアイコンは無効になります。

. [WORM *]ページで、クラスタのコンプライアンスクロックの保持期間を設定します。
+
詳細については、を参照してください https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["ONTAPのドキュメント：コンプライアンスクロックの初期化"^]。

. [設定]*をクリックします。


.完了後
機能パネルで* WORM *のステータスを確認できます。WORMを有効にすると、SnapLockライセンスが自動的にクラスタにインストールされます。SnapLockライセンスはONTAP System Managerで確認できます。



== WORMファイルを削除しています

privileged delete機能を使用して、保持期間中にWORMファイルを削除できます。

手順については、を参照してください https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["ONTAP のドキュメント"^]。



== WORMとデータの階層化

Cloud Volumes ONTAP 9.8以降の新規システムを作成する場合は、データ階層化とWORMストレージの両方を有効にすることができます。WORMストレージによるデータ階層化を有効にすると、データをクラウドのオブジェクトストアに階層化できます。

データ階層化とWORMストレージの両方を有効にする場合は、次の点に注意してください。

* オブジェクトストレージに階層化されたデータには、ONTAP のWORM機能は含まれていません。WORMの機能をエンドツーエンドで維持するには、バケットの権限を正しく設定する必要があります。
* オブジェクトストレージに階層化されたデータはWORM機能を保持しません。つまり、バケットとコンテナへのフルアクセス権を持つ技術的には、ONTAP によって階層化されたオブジェクトをだれでも削除できます。
* Cloud Volumes ONTAP 9.8へのリバートまたはダウングレードは、WORMと階層化を有効にしたあとはブロックされます。




== 制限

* Cloud Volumes ONTAP の WORM ストレージは、「信頼されたストレージ管理者」モデルで機能します。WORM ファイルは書き換えから保護されますが、期限切れ前の WORM データがボリュームに含まれていた場合でも、クラスタ管理者はボリュームを削除できます。
* 信頼できるストレージ管理者モデルに加えて、 Cloud Volumes ONTAP の WORM ストレージも「信頼できるクラウド管理者」モデルで暗黙的に動作します。クラウド管理者は、クラウドプロバイダからクラウドストレージを直接削除または編集することで、WORMデータを有効期限前に削除できます。


.関連リンク
* link:reference-worm-snaplock.html["WORMストレージ用の改ざん防止Snapshotコピーを作成"]

