---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage 
summary: Cloud Volumes ONTAP システム上で Write Once Read Many （ WORM ）ストレージをアクティブにして、指定した保存期間内にファイルを変更せずに保持できます。クラウド WORM ストレージには SnapLock テクノロジが採用されており、 WORM ファイルはファイルレベルで保護されます。 
---
= WORM ストレージ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP システム上で Write Once Read Many （ WORM ）ストレージをアクティブにして、指定した保存期間内にファイルを変更せずに保持できます。クラウド WORM ストレージには SnapLock テクノロジが採用されており、 WORM ファイルはファイルレベルで保護されます。



== WORM ストレージの仕組み

WORM ストレージにコミットされたファイルは、保持期間が過ぎたあとも変更することはできません。改ざん防止クロックは、 WORM ファイルの保持期間が経過したタイミングを決定します。

保存期間が経過すると、不要になったファイルを削除する必要があります。



== WORM ストレージのアクティブ化

WORMストレージをアクティブ化する方法は、使用しているCloud Volumes ONTAP のバージョンによって異なります。



=== バージョン9.10.1以降

Cloud Volumes ONTAP 9.10.1以降では、ボリュームレベルでWORMを有効または無効にすることができます。WORMを有効にする方法はニーズによって異なります。

新しいCloud Volumes ONTAP 作業環境を作成する場合は、WORMストレージを有効または無効にするように求められます。

* 作業環境の作成時にWORMストレージを有効にすると、BlueXPで作成したすべてのボリュームでWORMが有効になります。ただし、System ManagerまたはCLIを使用して、WORMを無効にしたボリュームを作成できます。
+
WORMストレージ専用のシステムを作成する場合は、このオプションを選択することを推奨します。

* 作業環境の作成時にWORMストレージを無効にすると、BlueXPで作成したすべてのボリュームでWORMが無効になります。ただし、System ManagerまたはCLIを使用して、WORMが有効なボリュームを作成できます。
+
同じシステム上に異なるタイプのボリュームを混在させる場合は、このオプションを選択することを推奨します。



どちらのオプションを選択してもかまいません <<充電中,充電の仕組みを理解する>>。



=== バージョン9.10.0以前

新しい作業環境を作成するときに、 Cloud Volumes ONTAP システムで WORM ストレージをアクティブにできます。個々のボリュームで WORM ストレージをアクティブ化することはできません -- WORM はシステムレベルでアクティブ化する必要がありますアクティブ化できるのは、作業環境を作成した場合のみです。



== 充電中

WORM ストレージの充電は、合計プロビジョニング容量に基づいて 1 時間ごとに行われます。

Cloud Volumes ONTAP 9.10.1以降では、次の充電動作について理解しておく必要があります。

* ONTAP 9.10.1以降では、WORMボリュームとWORM以外のボリュームを同じアグリゲートに配置できるようになりました。
* Cloud Volumes ONTAP 作業環境の作成時にWORMを有効にすると、BlueXPで作成したすべてのボリュームでWORMが有効になります。ただし、ONTAP CLIまたはSystem Managerを使用して、WORMを無効にしたボリュームを作成できます。これらのボリュームはWORM状態のままです。
* 作業環境の作成時にWORMを有効にしないと、BlueXPで作成したすべてのボリュームでWORMが無効になります。これらのボリュームのWORMレートでは課金されません。ただし、ONTAP CLIまたはSystem Managerを使用してWORM対応ボリュームを作成することができます。これらのボリュームはWORM状態に基づいて料金が請求されます。


https://cloud.netapp.com/pricing["WORM ストレージの価格設定については、こちらをご覧ください"^]



== ファイルを WORM にコミットしています

アプリケーションを使用して、 NFS または CIFS を介してファイルを WORM にコミットしたり、 ONTAP CLI を使用してファイルを WORM に自動コミットしたりできます。また、追記可能 WORM ファイルを使用して、ログ情報のように増分的に書き込まれるデータを保持することもできます。

Cloud Volumes ONTAP システムで WORM ストレージをアクティブにした後は、 WORM ストレージのすべての管理に ONTAP CLI を使用する必要があります。手順については、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["ONTAP のドキュメント"^]。



== 制限

* Cloud Volumes ONTAP の WORM ストレージは、「信頼されたストレージ管理者」モデルで機能します。WORM ファイルは書き換えから保護されますが、期限切れ前の WORM データがボリュームに含まれていた場合でも、クラスタ管理者はボリュームを削除できます。
* 信頼できるストレージ管理者モデルに加えて、 Cloud Volumes ONTAP の WORM ストレージも「信頼できるクラウド管理者」モデルで暗黙的に動作します。クラウド管理者は、クラウドプロバイダからクラウドストレージを直接削除するか、編集することで、有効期限が切れる前に WORM データを削除できました。
* WORM ストレージをアクティブ化すると、オブジェクトストレージへのデータ階層化を有効にできません。

