---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Cloud Volumes ONTAP には、いくつかのライセンスオプションがあります。それぞれのオプションを使用することで、ニーズに合わせた構成を選択できます。 
---
= Cloud Volumes ONTAP のライセンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP には、いくつかのライセンスオプションがあります。それぞれのオプションで、ニーズに合った消費モデルを選択できます。



== ライセンスの概要

新規のお客様は、次のライセンスオプションを利用できます。

容量単位のライセンス:: ネットアップアカウントで複数のCloud Volumes ONTAP システムをプロビジョニングした容量分だけ料金が発生追加のクラウドデータサービスを購入できます。容量ベースライセンスの消費モデルの詳細については、を参照してくださいlink:concept-licensing-charging.html["容量ベースのライセンスに関する詳細情報"]。
Keystoneサブスクリプション:: ハイアベイラビリティ（HA）ペアに対してシームレスなハイブリッドクラウドエクスペリエンスを提供する、従量課金制のサブスクリプションベースのサービスです。


以降のセクションでは、これらの各オプションについて詳しく説明します。


NOTE: ライセンスがないと、ライセンスされた機能の使用はサポートされません。



== 容量単位のライセンス

容量ベースのライセンスパッケージを使用すると、TiB分の容量に対してCloud Volumes ONTAP の料金を支払うことができます。このライセンスはネットアップアカウントに関連付けられており、ライセンスで十分な容量が使用可能であれば、ライセンスに対して複数のシステムを充電することができます。

たとえば、 20TiB のライセンスを 1 つ購入して 4 つの Cloud Volumes ONTAP システムを導入し、各システムに 5TiB のボリュームを割り当てて合計 20TiB にするとします。そのアカウントに導入されている各 Cloud Volumes ONTAP システムのボリュームで容量を使用できます。

容量ベースのライセンスは、 a_packag_ の形式で用意されています。Cloud Volumes ONTAP システムを導入する際には、ビジネスニーズに応じて、複数のライセンスパッケージから選択できます。


NOTE: BlueXPで管理される製品とサービスの実際の使用量と計測値は常にGiBとTiBで計算されますが、GB / GiBとTB / TiBという用語は同じ意味で使用されます。これは、Cloud Marketplaceのリスト、価格見積もり、リストの説明、およびその他の関連ドキュメントに反映されます。



=== パッケージ

Cloud Volumes ONTAP で使用できる容量ベースのパッケージは次のとおりです。容量ベースのライセンスパッケージの詳細については、を参照してくださいlink:concept-licensing-charging.html["容量ベースのライセンスに関する詳細情報"]。

次の容量ベースパッケージでサポートされるVMタイプの一覧については、を参照してください。

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure でサポートされる構成"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud でサポートされている構成"^]


endif::gcp[]



==== フリーミアム

Cloud Volumes ONTAP のすべての機能をネットアップから無償で提供（クラウドプロバイダの料金がまだ適用されます）。

* ライセンスや契約は必要ありません。
* ネットアップによるサポートは含まれていません。
* Cloud Volumes ONTAP システムあたりのプロビジョニング可能な容量は 500GiB に制限されています。
* ネットアップのアカウント 1 つにつき、最大 10 台の Cloud Volumes ONTAP システムを任意のクラウドプロバイダで使用できます。
* Cloud Volumes ONTAP システム用にプロビジョニングされた容量が500GiBを超えると、BlueXPはシステムをEssentialsパッケージに変換します。
+
システムがEssentialsパッケージに変換されるとすぐに、がlink:concept-licensing-charging.html#minimum-charge["最小充電"]適用されます。

+
プロビジョニングされた容量が 500GiB 未満の他のシステムは、 Freemium （ Freemium 製品を使用して導入されている場合）に残ります。





==== Essentialsをクリックします

容量単位での支払いには、次のようなさまざまな構成が用意されています。

* Cloud Volumes ONTAP 構成を選択します。
+
** シングルノードまたは HA システム
** ディザスタリカバリ（ DR ）用のファイルストレージとブロックストレージまたはセカンダリデータ


* ネットアップのクラウドデータサービスを追加コストで利用できます




==== 最適化

プロビジョニングされた容量とI/O処理の料金は別途お支払いください。

* Cloud Volumes ONTAP のシングルノードまたはHA
* 充電は、ストレージと使用量（I/O）の2つのコストコンポーネントに基づいて行われます。
+
データレプリケーション（SnapMirror）、バックアップ（SnapVault）、NDMPに関連するI/Oは課金されません。



ifdef::azure[]

* Azure Marketplaceでは、従量課金制または年間契約として提供されています


endif::azure[]

ifdef::gcp[]

* Google Cloud Marketplaceでは、従量課金制サービスまたは年間契約として提供されます


endif::gcp[]

* ネットアップのクラウドデータサービスを追加コストで利用できます




==== プロフェッショナル

バックアップの数に制限はなく、あらゆる種類のCloud Volumes ONTAP 構成で容量ごとに料金が発生します。

* Cloud Volumes ONTAP 構成のライセンスを提供します
+
プライマリボリュームとセカンダリボリュームの容量を同じ速度で課金する、シングルノードまたはHA

* BlueXPのバックアップとリカバリを使用したボリュームバックアップは無制限ですが、Professionalパッケージを使用するCloud Volumes ONTAPシステムのみが対象です。
+

NOTE: BlueXP  のバックアップとリカバリには従量課金制（PAYGO）サブスクリプションが必要ですが、このサービスの使用料金は発生しません。BlueXP  バックアップ/リカバリのライセンス設定の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["BlueXPのバックアップとリカバリのライセンスをセットアップ"^]。

* ネットアップのクラウドデータサービスを追加コストで利用できます




=== ヨウリヨウヘエスライセンスノシヨウカノウ

Cloud Volumes ONTAPシステムでPAYGOライセンスとBYOLライセンスを利用できるようにするには、BlueXP  Connectorが稼働している必要があります。詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["コネクタについて説明します"^]。



=== 開始方法

容量単位のライセンスの取得方法については、以下をご覧ください。

ifdef::aws[]

* link:task-set-up-licensing-aws.html["AWSでCloud Volumes ONTAP のライセンスを設定"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["AzureでCloud Volumes ONTAP のライセンスをセットアップする"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Google CloudでCloud Volumes ONTAP のライセンスを設定します"]


endif::gcp[]



== Keystoneサブスクリプション

成長に合わせて拡張できるサブスクリプションベースのサービス。運用コストの消費モデルを希望するお客様に、設備投資やリースを先行するお客様にシームレスなハイブリッドクラウドエクスペリエンスを提供します。

課金は、Keystoneサブスクリプションに含まれる1つ以上のCloud Volumes ONTAP HAペアのコミット済み容量に基づいて行われます。

各ボリュームのプロビジョニング済み容量は集計され、Keystoneサブスクリプションのコミット済み容量と定期的に比較されます。超過した容量はKeystoneサブスクリプションのバーストとして課金されます。

link:https://docs.netapp.com/us-en/keystone-staas/index.html["NetApp Keystoneの詳細については、こちらをご覧ください"^]。



=== サポートされている構成

KeystoneサブスクリプションはHAペアでサポートされます。現時点では、このライセンスオプションはシングルノードシステムではサポートされていません。



=== 容量制限

個々の Cloud Volumes ONTAP システムでは、ディスクとオブジェクトストレージへの階層化によって、最大 2 PiB の容量をサポートしています。



=== 開始方法

Keystoneサブスクリプションの利用を開始する方法をご確認ください。

ifdef::aws[]

* link:task-set-up-licensing-aws.html["AWSでCloud Volumes ONTAP のライセンスを設定"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["AzureでCloud Volumes ONTAP のライセンスをセットアップする"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Google CloudでCloud Volumes ONTAP のライセンスを設定します"]


endif::gcp[]



== ノードベースのライセンス

ノードベースのライセンスは、 Cloud Volumes ONTAP のライセンスをノード単位で付与することが可能になった旧世代のライセンスモデルです。このライセンスモデルは新規のお客様にはご利用いただけません。ノード単位の充電は、前述のキャパシティ単位の充電方法に置き換えられました。

NetAppでは、ノードベースのライセンスの販売終了（EOA）とサポート終了（EOS）を計画しています。EOAおよびEOS後は、ノードベースのライセンスを容量ベースのライセンスに変換する必要があります。

詳細については、を参照して https://mysupport.netapp.com/info/communications/CPC-00589.html["お客様とのコミュニケーション：CPC-00589"^]ください。



=== ノードベースライセンスの販売終了

2024年11月11日より、ノードベースライセンスの限定的な可用性が終了しました。ノードベースのライセンスのサポートは2024年12月31日に終了します。

有効なノードベースの契約がEOA日を超えている場合は、契約が期限切れになるまでライセンスを引き続き使用できます。契約が期限切れになったら、容量ベースのライセンスモデルに移行する必要があります。Cloud Volumes ONTAPノードの長期契約をお持ちでない場合は、EOS日までに変換を計画することが重要です。

各ライセンスタイプの詳細と、EOAがライセンスタイプに与える影響については、次の表を参照してください。

[cols="2*"]
|===
| ライセンスタイプ | EOA後の影響 


 a| 
お客様所有のライセンスを使用（BYOL）から購入した、有効なノードベースライセンス
 a| 
ライセンスは有効期限まで有効です。未使用の既存のノードベースライセンスを新しいCloud Volumes ONTAPシステムの導入に使用できます。



 a| 
BYOLから購入した、期限切れのノードベースライセンス
 a| 
このライセンスを使用して新しいCloud Volumes ONTAPシステムを導入する権利はありません。既存のシステムは引き続き機能する可能性がありますが、EOS日以降はシステムのサポートや更新を受けることはできません。



 a| 
PAYGOサブスクリプションを含む有効なノードベースライセンス
 a| 
は、容量ベースのライセンスに移行するまで、EOS日以降はNetAppサポートの提供を停止します。

|===
.対象外事項
NetAppは、特定の状況について特別な考慮が必要であると認識しており、以下の場合はノードベースライセンスのEOAおよびEOSは適用されません。

* 米国公共機関のお客様
* プライベートモードでの導入
* AWSでのCloud Volumes ONTAPの中国リージョン導入


これらの特定のシナリオでは、NetAppは、契約上の義務と運用上のニーズに準拠して、固有のライセンス要件に対処するためのサポートを提供します。


NOTE: このような場合でも、新しいノードベースライセンスとライセンスの更新は、承認日から最長1年間有効です。



== ライセンスの変換

BlueXP  では、ライセンス変換ツールを使用して、ノードベースのライセンスを容量ベースにシームレスに変換できます。ノードベースライセンスの販売終了（EOA）については、を参照してくださいlink:concept-licensing.html#end-of-availability-of-node-based-licenses["ノードベースライセンスの販売終了"]。

移行する前に、2つのライセンスモデルの違いを理解しておくことをお勧めします。ノードベースのライセンスには、ONTAPインスタンスごとに容量が固定されているため、柔軟性が制限される場合があります。一方、容量ベースのライセンスでは、複数のインスタンスにまたがるストレージプールを共有できるため、柔軟性が向上し、リソース利用率が最適化され、ワークロードを再配分する際の金銭的なペナルティが軽減されます。容量ベースの充電は、変化するストレージ要件に合わせてシームレスに調整できます。

この変換方法については、を参照してくださいlink:task-convert-node-capacity.html["Cloud Volumes ONTAPノードベースライセンスを容量ベースライセンスに変換する"]。


NOTE: システムを容量ベースのライセンスからノードベースのライセンスに変換することはできません。
