---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging 
summary: 容量ベースのライセンスの充電、消費モデル、価格設定、構成について理解しておく必要があります。 
---
= Cloud Volumes ONTAPの容量ベースライセンスに関する詳細情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量ベースのライセンスの課金と使用容量について理解しておく必要があります。



== 消費モデル

容量ベースのライセンスパッケージには、次の消費モデルがあります。

* * BYOL *：お客様所有のライセンスを使用（BYOL）。NetAppから購入したライセンスで、任意のクラウドプロバイダでCloud Volumes ONTAPを導入するために使用できます。


ifdef::azure[]

+ BYOLではOptimizedパッケージを使用できないことに注意してください。

endif::azure[]

* * PAYGO *：従量課金制（PAYGO）サブスクリプションは、クラウドプロバイダのマーケットプレイスから提供される時間単位のサブスクリプションです。
* * Annual *：クラウドプロバイダの市場から年間契約。


次の点に注意してください。

* ネットアップからライセンスを購入した場合（ BYOL ）は、クラウドプロバイダが提供する PAYGO のサブスクリプションも必要です。
+
ライセンスは常に最初に請求されますが、次の場合は、マーケットプレイスで 1 時間ごとの料金が請求されます。

+
** ライセンス容量を超えた場合
** ライセンスの期間が終了する場合


* 市場から年間契約を結んでいる場合、導入する Cloud Volumes ONTAP システムにはその契約が適用されます。BYOL と年間市場契約を組み合わせることはできません。
* 中国のリージョンでは、BYOLを使用するシングルノードシステムのみがサポートされます。




== パッケージの変更

導入後、容量ベースのライセンスを使用するCloud Volumes ONTAP システムのパッケージを変更できます。たとえば、Essentialsパッケージを含むCloud Volumes ONTAP システムを導入した場合、ビジネスニーズの変化に応じて、そのシステムをProfessionalパッケージに変更できます。

link:task-manage-capacity-licenses.html["充電方法を変更する方法について説明します"]。

ノードベースライセンスから容量ベースライセンスへの変換の詳細については、を参照してください。



== 価格設定とサポートされる構成

価格設定の詳細については、を参照してください https://bluexp.netapp.com/pricing/["NetApp BlueXPのWebサイト"^]。

容量ベースのライセンスパッケージは Cloud Volumes ONTAP 9.7 以降で利用できます。



=== Storage VMs

* データ提供用の Storage VM （ SVM ）を追加する場合、追加のライセンスコストは発生しませんが、データ提供用 SVM ごとの容量は 4TiB になります。
* ディザスタリカバリ用 SVM は、プロビジョニングされた容量に基づいて料金が発生します。




=== HA ペア

HA ペアの場合、ノードのプロビジョニング済み容量に対してのみ料金が発生します。パートナーノードに同期ミラーリングされるデータには料金は発生しません。



=== FlexCloneボリュームとFlexCache ボリューム

* FlexClone ボリュームで使用される容量に対する料金は発生しません。
* ソースおよびデスティネーションの FlexCache ボリュームはプライマリデータとみなされ、プロビジョニング済みスペースに基づいて料金が発生します。




== 容量制限

このライセンスモデルでは、個々の Cloud Volumes ONTAP システムでディスクとオブジェクトストレージへの階層化によって、最大 2 PiB の容量をサポートします。

ライセンス自体にに関しては、最大容量制限はありません。



== システムの最大数

容量単位のライセンスを使用する場合、Cloud Volumes ONTAP システムの最大数はネットアップアカウントあたり20個に制限されます。a_system_は、Cloud Volumes ONTAP HAペア、Cloud Volumes ONTAP シングルノードシステム、またはユーザが作成した追加のStorage VMです。デフォルトのStorage VMはカウントされません。これにより、環境 のすべてのライセンスモデルが制限されます。

たとえば、次の3つの作業環境があるとします。

* 1つのStorage VMを含むシングルノードのCloud Volumes ONTAP システム（Cloud Volumes ONTAP の導入時に作成されるデフォルトのStorage VM）
+
この作業環境は1つのシステムとしてカウントされます。

* 2つのStorage VMを含むシングルノードのCloud Volumes ONTAP システム（デフォルトのStorage VMと、作成した追加のStorage VM 1台）
+
この作業環境は、シングルノードシステム用と追加のStorage VM用の2つのシステムとしてカウントされます。

* 3つのStorage VMを含むCloud Volumes ONTAP HAペア（デフォルトのStorage VMと、作成した追加のStorage VM 2つ）
+
この作業環境は、HAペア用と追加のStorage VM用の2つという3つのシステムとしてカウントされます。



合計6つのシステムです。その後、アカウントに14台のシステムを追加するためのスペースを確保します。

20台以上のシステムを必要とする大規模な導入環境の場合は、アカウント担当者または営業チームにお問い合わせください。

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["ネットアップアカウントの詳細については、こちらをご覧ください"^]。



== 充電に関するメモ

以下の詳細は、課金が容量ベースのライセンスとどのように連携するかを理解するのに役立ちます。



=== 最低料金

プライマリ（読み取り/書き込み）ボリュームが1つ以上あるStorage VMをデータ提供する場合は、最小4TiBの料金が発生します。プライマリボリュームの合計が4TiBを下回った場合、BlueXPはそのStorage VMに4TiBの最小料金を適用します。

まだボリュームをプロビジョニングしていない場合は、最小料金は適用されません。

Essentialsパッケージの場合、4TiBの最小容量料金は、セカンダリ（データ保護）ボリュームのみを含むStorage VMには適用されません。たとえば、1TiBのセカンダリデータが格納されたStorage VMがある場合、その1TiBのデータに対してのみ課金されます。Essentials以外のパッケージタイプ（OptimizedおよびProfessional）では、ボリュームタイプに関係なく、最小容量4TiBが適用されます。



=== 年齢が高すぎます

BYOLの容量を超えた場合やライセンスの有効期限が切れた場合は、マーケットプレイスのサブスクリプションに基づく時間単位の料金で超過分の料金が請求されます。超過分はマーケットプレイスの料金で課金され、最初に他のライセンスの使用可能な容量を優先的に使用することができます。



=== Essentials パッケージ

Essentialsパッケージでは、導入タイプ（HAまたはシングルノード）とボリュームタイプ（プライマリまたはセカンダリ）ごとに課金されます。高から低の価格は、_Essentials Primary HA_、_Essentials Primary Single Node_、_Essentials Secondary HA_、および_Essentials Secondary Single Node_の順になります。また、マーケットプレイス契約を購入した場合やプライベートオファーに同意した場合でも、どのような導入やボリュームタイプでも容量料金は同じです。

ライセンスは、Cloud Volumes ONTAPシステム内で作成されたボリュームタイプのみに基づいています。

* Essentialsシングルノード：1つのONTAPノードのみを使用してCloud Volumes ONTAPシステムに作成された読み取り/書き込みボリューム。
* Essentials HA：2つのONTAPノードを使用する読み取り/書き込みボリュームで、相互にフェイルオーバーして無停止のデータアクセスを実現します。
* Essentialsセカンダリシングルノード：1つのONTAPノードのみを使用するCloud Volumes ONTAPシステムで作成されるデータ保護（DP）タイプのボリューム（通常は読み取り専用のSnapMirrorまたはSnapVaultデスティネーションボリューム）。
+

NOTE: 読み取り専用/ DPボリュームがプライマリボリュームになった場合、BlueXP  はそのボリュームをプライマリデータとみなし、ボリュームが読み取り/書き込みモードであった時間に基づいて課金コストを計算します。ボリュームが再び読み取り専用/ DPに設定されると、BlueXP  は再びそのボリュームをセカンダリデータと見なし、デジタルウォレット内の最適なライセンスを使用して課金します。

* EssentialsセカンダリHA：データ保護（DP）タイプのボリューム（通常は読み取り専用のSnapMirrorまたはSnapVaultデスティネーションボリューム）。2つのONTAPノードを使用してCloud Volumes ONTAPシステムで作成され、無停止のデータアクセス用に相互にフェイルオーバーできる。


.BYOL
EssentialsライセンスをNetApp（BYOL）から購入し、その環境およびボリュームタイプでライセンスされている容量を超えた場合、BlueXPデジタルウォレットは、より高い価格のEssentialsライセンス（使用可能な容量がある場合）に対して追加料金を請求します。これは、市場に課金する前に、前払い済みの容量として購入済みの使用可能容量を最初に使用するためです。BYOLライセンスで使用できる容量がない場合は、超過した容量に対して、マーケットプレイスでオンデマンドの時間単位料金（PAYGO）で課金され、月単位の請求書にコストが追加されます。

次に例を示します。Essentialsパッケージには、次のライセンスがあるとします。

* 500TiBのコミット済み容量を含む500TiBのセカンダリHA_License
* 100TiBのコミット済み容量のみを含む500TiB _ Essentialsシングルノードライセンス


セカンダリボリュームを含むHAペアにはもう1つの50TiBがプロビジョニングされます。BlueXPデジタルウォレットは、その50TiBをPAYGOに課金する代わりに、_Essentials Single Node_licenseに対して50TiBの超過料金を請求します。このライセンスの価格は_Essentials Secondary HA_よりも高く設定されていますが、すでに購入したライセンスを使用しているため、毎月の請求書にコストが追加されることはありません。

BlueXPデジタルウォレットでは、_Essentials Single Node_licenseに対して請求される50TiBが表示されます。

別の例を見てみましょうEssentialsパッケージには、次のライセンスがあるとします。

* 500TiBのコミット済み容量を含む500TiBのセカンダリHA_License
* 100TiBのコミット済み容量のみを含む500TiB _ Essentialsシングルノードライセンス


プライマリボリュームを含むHAペアにも100TiBがプロビジョニングされます。購入したライセンスには_EssentialsプライマリHA_committed容量がありません。_EssentialsプライマリHA_LICENSEは、_EssentialsプライマリSingle Node_and_EssentialsセカンダリHA_LICENSESよりも価格が高くなります。

この例では、BlueXPのデジタルウォレットは、追加の100TiBに対してマーケットプレイスのレートで超過料金を請求しています。超過料金は毎月の請求書に表示されます。

.マーケットプレイス契約またはプライベートオファー
マーケットプレイス契約またはプライベートオファーの一部としてEssentialsライセンスを購入した場合、BYOLロジックは適用されず、使用に応じた正確なライセンスタイプが必要です。ライセンスタイプには、ボリュームタイプ（プライマリまたはセカンダリ）と導入タイプ（HAまたはシングルノード）が含まれます。

たとえば、Essentialsライセンスを使用してCloud Volumes ONTAPインスタンスをデプロイするとします。次に、読み書き可能ボリューム（プライマリシングルノード）と読み取り専用ボリューム（セカンダリシングルノード）をプロビジョニングします。Marketplace契約またはプライベートオファーには、プロビジョニングされた容量をカバーするために、_Essentials Single Node_and_Essentials Secondary Single Node _の容量が含まれている必要があります。マーケットプレイス契約やプライベートオファーに含まれていないプロビジョニング済み容量には、オンデマンドの時間単位料金（PAYGO）が適用され、月 々 の請求書にコストが追加されます。
