---
sidebar: sidebar 
permalink: concept-active-iq.html 
keywords: autosupport, digital advisor, active iq digital advisor, telemetry 
summary: ONTAP の AutoSupport コンポーネントはテレメトリを収集し、分析用に送信します。Digital Advisorは、AutoSupportからのデータを分析し、プロアクティブなサポートと最適化を提供します。Digital Advisorは、人工知能を使用して潜在的な問題を特定し、ビジネスに影響が及ぶ前に問題を解決できるよう支援します。 
---
= AutoSupportとDigital AdvisorがCloud Volumes ONTAPにどのように使用されているかをご確認ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP の AutoSupport コンポーネントはテレメトリを収集し、分析用に送信します。Active IQデジタルアドバイザ（別名デジタルアドバイザ）は、AutoSupportからのデータを分析し、プロアクティブなサポートと最適化を提供します。Digital Advisorは、人工知能を使用して潜在的な問題を特定し、ビジネスに影響が及ぶ前に問題を解決できるよう支援します。

Digital Advisorは、クラウドベースのポータルとモバイルアプリを通じて、実用的な予測分析とプロアクティブなサポートを提供することで、グローバルハイブリッドクラウド全体にわたってデータインフラを最適化します。SupportEdgeと有効な契約を結んでいるNetAppのすべてのお客様が、デジタルアドバイザによるデータ主体の分析情報と推奨事項を利用できます（機能は製品やサポートレベルによって異なります）。

Digital Advisorでできることは次のとおりです。

* アップグレードを計画する。
+
Digital Advisorは、新しいバージョンのONTAPにアップグレードすることで解決できる環境内の問題を特定し、Upgrade Advisorコンポーネントがアップグレードの計画を支援します。

* システムの健全性を表示します。
+
Digital Advisorのダッシュボードに健全性に関する問題が報告され、問題の修正に役立ちます。システム容量を監視して、ストレージスペースが不足しないようにします。システムのサポートケースを表示します。

* パフォーマンスを管理
+
デジタルアドバイザでは、ONTAPシステムマネージャよりも長い期間のシステムパフォーマンスが表示されます。パフォーマンスに影響を与えている構成やシステムの問題を特定します。
効率性の最大化Storage Efficiency 指標を表示し、より多くのデータをより少ないスペースに格納する方法を特定します。

* インベントリと構成を表示します。
+
Digital Advisorは、完全なインベントリおよびソフトウェアとハードウェアの構成情報を表示します。サービス契約がいつ期限切れになるかを確認し、サービス契約を更新してサポートを継続するかを確認します。



.関連リンク
* https://docs.netapp.com/us-en/active-iq/["NetAppのドキュメント：デジタルアドバイザ"^]
* https://aiq.netapp.com/custom-dashboard/search["Digital Advisorを起動"^]
* https://www.netapp.com/us/services/support-edge.aspx["SupportEdge サービス"^]

