---
settings:
  name: Cloud Volumes ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: クラウドプロバイダ
    default: すべてのクラウドプロバイダ
    options:
    - name: Amazon Web Services の
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: ja-jp,us-en,zh-cn,zh-tw,ko-kr
sidebar:
  entries:
  - title: Cloud Volumes ONTAP のドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 既知の制限
      url: "/reference-limitations.html"
    - title: Cloud Volumes ONTAP リリースノート
      url: "/whats-new-ontap.html"
  - title: はじめに
    entries:
    - title: Cloud Volumes ONTAP の詳細をご覧ください
      url: "/concept-overview-cvo.html"
    - title: Amazon Web Services の利用を開始しましょう
      flavor: aws
      entries:
      - title: クイックスタート
        url: "/task-getting-started-aws.html"
      - title: 構成を計画
        url: "/task-planning-your-config.html"
      - title: ネットワークをセットアップします
        entries:
        - title: ネットワーク要件
          url: "/reference-networking-aws.html"
        - title: AWS 転送ゲートウェイを設定します
          url: "/task-setting-up-transit-gateway.html"
        - title: HAペアを共有サブネットに導入します
          url: "/task-deploy-aws-shared-vpc.html"
        - title: AWS のセキュリティグループルール
          url: "/reference-security-groups.html"
      - title: AWS KMS を設定します
        url: "/task-setting-up-kms.html"
      - title: IAMロールを設定する
        url: "/task-set-up-iam-roles.html"
      - title: ライセンスをセットアップする
        url: "/task-set-up-licensing-aws.html"
      - title: AWS で Cloud Volumes ONTAP を起動します
        url: "/task-deploying-otc-aws.html"
      - title: AWS C2S で作業を開始する
        url: "/task-getting-started-aws-c2s.html"
    - title: Microsoft Azure で利用を開始しましょう
      flavor: azure
      entries:
      - title: クイックスタート
        url: "/task-getting-started-azure.html"
      - title: 構成を計画
        url: "/task-planning-your-config-azure.html"
      - title: ネットワークをセットアップします
        url: "/reference-networking-azure.html"
      - title: キーを使用して暗号化を設定します
        url: "/task-set-up-azure-encryption.html"
      - title: ライセンスをセットアップする
        url: "/task-set-up-licensing-azure.html"
      - title: ハイアベイラビリティモードを有効にします
        url: "/task-azure-high-availability-mode.html"
      - title: Azure で Cloud Volumes ONTAP を起動します
        url: "/task-deploying-otc-azure.html"
    - title: Google Cloud で始めましょう
      flavor: gcp
      entries:
      - title: クイックスタート
        url: "/task-getting-started-gcp.html"
      - title: 構成を計画
        url: "/task-planning-your-config-gcp.html"
      - title: ネットワークをセットアップします
        url: "/reference-networking-gcp.html"
      - title: VPC サービスコントロールを計画する
        url: "/reference-vpc-service-controls-gcp.html"
      - title: サービスアカウントを作成します
        url: "/task-creating-gcp-service-account.html"
      - title: お客様が管理する暗号化キーを使用します
        url: "/task-setting-up-gcp-encryption.html"
      - title: ライセンスをセットアップする
        url: "/task-set-up-licensing-google.html"
      - title: Google CloudでCloud Volumes ONTAP を起動します
        url: "/task-deploying-gcp.html"
  - title: Cloud Volumes ONTAP を使用します
    entries:
    - title: ライセンス管理
      entries:
      - title: 容量ベースのライセンスを管理します
        url: "/task-manage-capacity-licenses.html"
      - title: Keystone Flex Subscriptions を管理します
        url: "/task-manage-keystone.html"
      - title: ノードベースのライセンスを管理します
        url: "/task-manage-node-licenses.html"
    - title: ボリュームと LUN の管理
      entries:
      - title: ボリュームを作成します
        url: "/task-create-volumes.html"
      - title: 既存のボリュームを管理
        url: "/task-manage-volumes.html"
      - title: アクセス頻度の低いデータをオブジェクトストレージに階層化します
        url: "/task-tiering.html"
      - title: LUN をホストに接続します
        url: "/task-connect-lun.html"
      - title: FlexCache でデータアクセスを高速化
        url: "/task-accelerate-data-access.html"
    - title: アグリゲートの管理
      entries:
      - title: アグリゲートを作成する
        url: "/task-create-aggregates.html"
      - title: 既存のアグリゲートを管理する
        url: "/task-manage-aggregates.html"
      - title: 容量の設定を管理します
        url: "/task-manage-capacity-settings.html"
    - title: Storage VM 管理
      entries:
      - title: Cloud Manager で Storage VM を使用できます
        url: "/task-managing-svms.html"
      - title: AWS で Storage VM を作成します
        flavor: aws
        url: "/task-managing-svms-aws.html"
      - title: Azure で Storage VM を作成します
        flavor: azure
        url: "/task-managing-svms-azure.html"
      - title: Google CloudでStorage VMを作成します
        flavor: gcp
        url: "/task-managing-svms-gcp.html"
    - title: セキュリティとデータ暗号化
      entries:
      - title: ネットアップの暗号化機能でボリュームを暗号化
        url: "/task-encrypting-volumes.html"
      - title: Azure Key Vaultを使用してキーを管理します
        flavor: azure
        url: "/task-azure-key-vault.html"
      - title: Google Cloud KMSを使用してキーを管理します
        flavor: gcp
        url: "/task-google-key-manager.html"
      - title: ランサムウェアからの保護を強化
        url: "/task-protecting-ransomware.html"
    - title: システム管理
      entries:
      - title: Cloud Volumes ONTAP をアップグレードします
        url: "/task-updating-ontap-cloud.html"
      - title: 従量課金制システムを登録
        url: "/task-registering.html"
      - title: システムを停止して起動します
        url: "/task-managing-state.html"
      - title: システム時間を同期します
        url: "/task-sync-time.html"
      - title: システムの書き込み速度を変更する
        url: "/task-modify-write-speed.html"
      - title: システムパスワードを変更します
        url: "/task-change-password.html"
      - title: システムを追加、削除、または削除します
        entries:
        - title: 既存のシステムを追加します
          url: "/task-adding-systems.html"
        - title: 作業環境を削除します
          url: "/task-removing.html"
        - title: システムを削除します
          url: "/task-deleting-working-env.html"
      - title: AWSの管理
        flavor: aws
        entries:
        - title: EC2 インスタンスタイプを変更します
          url: "/task-change-ec2-instance.html"
        - title: HA ペアのルーティングテーブルを変更する
          url: "/task-change-route-tables.html"
        - title: AWS のコストを監視
          url: "/task-monitoring-costs.html"
      - title: Azureの管理
        flavor: azure
        entries:
        - title: Azure VM タイプを変更します
          url: "/task-change-azure-vm.html"
        - title: CIFS ロックを上書きする
          url: "/task-overriding-cifs-locks.html"
        - title: Azure Private Linkまたはサービスエンドポイントを使用する
          url: "/task-enabling-private-link.html"
      - title: Google Cloudの管理
        flavor: gcp
        entries:
        - title: マシンタイプを変更します
          url: "/task-change-gcp-machine.html"
      - title: System Managerで管理を行います
        url: "/task-administer-advanced-view.html"
      - title: CLIからの管理
        url: "/task-connecting-to-otc.html"
    - title: システムの健全性とイベント
      entries:
      - title: AutoSupport のセットアップを確認します
        url: "/task-verify-autosupport.html"
      - title: EMS を設定します
        url: "/task-configure-ems.html"
  - title: 概念
    entries:
    - title: ライセンス
      url: "/concept-licensing.html"
    - title: ストレージ
      entries:
      - title: クライアントプロトコル
        url: "/concept-client-protocols.html"
      - title: ディスクとアグリゲート
        url: "/concept-storage.html"
      - title: AWSのElastic Volumes
        flavor: aws
        url: "/concept-aws-elastic-volumes.html"
      - title: データの階層化
        url: "/concept-data-tiering.html"
      - title: ストレージ管理
        url: "/concept-storage-management.html"
      - title: 書き込み速度
        url: "/concept-write-speed.html"
      - title: Flash Cache
        url: "/concept-flash-cache.html"
      - title: WORM ストレージ
        url: "/concept-worm.html"
    - title: ハイアベイラビリティペア
      entries:
      - title: AWS の HA ペア
        flavor: aws
        url: "/concept-ha.html"
      - title: Azure の HA ペア
        flavor: azure
        url: "/concept-ha-azure.html"
      - title: GCP の HA ペア
        flavor: gcp
        url: "/concept-ha-google-cloud.html"
      - title: ストレージテイクオーバー中の操作
        url: "/concept-degraded-ha-pair.html"
    - title: セキュリティ
      url: "/concept-security.html"
    - title: パフォーマンス
      url: "/concept-performance.html"
    - title: ノードベースの BYOL の管理
      url: "/concept-license-management.html"
    - title: AutoSupport と Active IQ デジタルアドバイザ
      url: "/concept-active-iq.html"
    - title: デフォルト設定
      url: "/reference-default-configs.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: Cloud Volumes ONTAP の詳細をご覧ください
      url: concept-overview-cvo.html
    - title: AWS でのクイックスタート
      url: task-getting-started-aws.html
      flavor: aws
    - title: Azure のクイックスタート
      url: task-getting-started-azure.html
      flavor: azure
    - title: Google Cloud のクイックスタート
      url: task-getting-started-gcp.html
      flavor: gcp
  - title: ライセンス
    links:
    - title: ライセンスの概要
      url: concept-licensing.html
    - title: 容量ベースのライセンスを管理します
      url: task-manage-capacity-licenses.html
    - title: 未割り当てのノードベースライセンスを交換します
      url: task-manage-node-licenses.html#exchange-unassigned-node-based-licenses
    - title: Keystone Flex Subscriptions を管理します
      url: task-manage-keystone.html
  - title: ストレージ管理
    links:
    - title: ボリュームを作成します
      url: task-create-volumes.html
    - title: アクセス頻度の低いデータをオブジェクトストレージに階層化します
      url: task-tiering.html
    - title: FlexCache でデータアクセスを高速化
      url: task-accelerate-data-access.html
  - title: システム管理
    links:
    - title: Cloud Volumes ONTAP をアップグレードします
      url: task-updating-ontap-cloud.html
    - title: Cloud Volumes ONTAP を停止して起動します
      url: task-managing-state.html
  - title: セキュリティ
    links:
    - title: ネットアップの暗号化機能でボリュームを暗号化
      url: task-encrypting-volumes.html
    - title: ランサムウェアからの保護を強化
      url: task-protecting-ransomware.html
  - title: API
    links:
    - title: Cloud Volumes ONTAP API の概要
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/overview.html
    - title: API を使用する準備をします
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/prepare.html
    - title: API リファレンス
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_resources.html
  - title: トラブルシューティング
    links:
    - title: ネットアップナレッジベース
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)
  - title: 参照
    links:
    - title: サポートされている構成
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html
    - title: サポートされるクラウドリージョン
      url: https://cloud.netapp.com/cloud-volumes-global-regions
    - title: 計算機
      url: https://cloud.netapp.com/calculator-hub
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Cloud-Volumes-ONTAP/bd-p/CloudVolumes
    - title: Cloud Central のブログです
      url: https://cloud.netapp.com/blog/topic/cloud-volumes-ontap
    - title: クラウドに関する Web セミナー
      url: https://cloud.netapp.com/events
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: Cloud Manager のすべてのドキュメント
