---
sidebar: sidebar 
permalink: reference-worm-snaplock.html 
keywords: WORM, SnapLock, Snapshot copies, 
summary: Cloud Volumes ONTAPシステム上にWrite Once Read Many（WORM）ファイルの改ざんを防止し、Snapshotを変更せずに特定の保持期間にわたって保持できます。 
---
= WORMストレージ用の改ざん防止Snapshotコピーを作成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAPシステム上にWrite Once Read Many（WORM）ファイルの改ざんを防止し、Snapshotを変更せずに特定の保持期間にわたって保持できます。この機能はSnapLockテクノロジを基盤としており、データ保護とコンプライアンスのレイヤを追加します。

.作業を開始する前に
Snapshotコピーの作成に使用するボリュームがSnapLockボリュームであることを確認します。ボリュームでSnapLock保護を有効にする方法については、を参照し https://docs.netapp.com/us-en/ontap/snaplock/snaplock-config-overview-concept.html["ONTAPのドキュメント：「Configure SnapLock」"^]てください。

.手順
. SnapLockボリュームからSnapshotコピーを作成します。CLIまたはSystem Managerを使用したSnapshotコピーの作成については、を参照して https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["ONTAPのドキュメント：ローカルSnapshotコピーの管理の概要"^]ください。
+
SnapshotコピーはボリュームのWORMプロパティを継承し、改ざんを防止します。基盤となるSnapLockテクノロジにより、指定した保持期間が経過するまで、Snapshotの編集や削除が行われないように保護されます。

. これらのSnapshotを編集する必要がある場合は、保持期間を変更できます。詳細については、を参照して https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html#set-the-default-retention-period["ONTAPのドキュメント：保持期限の設定"^]ください。



NOTE: Cloud Volumes ONTAPのWORMストレージは「信頼されたストレージ管理者」モデルで動作するため、Snapshotコピーが特定の保持期間にわたって保護されていても、クラスタ管理者はソースボリュームを削除できます。また、信頼できるクラウド管理者は、クラウドストレージリソースを操作することでWORMデータを削除できます。
