---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Azure MarketplaceからCloud Volumes ONTAPを導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure Marketplaceの直接導入を使用すると、Cloud Volumes ONTAPをすばやく簡単に導入できます。Azure Marketplaceでは、数回のクリックでCloud Volumes ONTAPを迅速に導入し、自社環境の中核的な機能を確認できます。

このサービスの詳細については、を参照してくださいlink:concept-azure-mktplace-direct.html["BlueXP  と市場で提供されているCloud Volumes ONTAPソリューションの詳細を確認する"]。

.このタスクについて
Azure Marketplaceを使用して導入されたCloud Volumes ONTAPシステムには、次のプロパティがあります。Azure Marketplaceを介して導入されたスタンドアロンインスタンスの機能は、BlueXP  で検出されると変更されます。

* 最新のCloud Volumes ONTAPバージョン（9.16.1以降）。
* プロビジョニング可能な容量が500GiBに制限されているCloud Volumes ONTAPの無償ライセンス。このライセンスにはNetAppのサポートは含まれておらず、有効期限はありません。
* 単一のアベイラビリティゾーン（AZ）内にハイアベイラビリティ（HA）モードで構成され、デフォルトのシリアル番号でプロビジョニングされた2つのノード。Storage Virtual Machine（Storage VM）はに導入されlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["柔軟なオーケストレーションモード"]ます。
* デフォルトで作成されるインスタンスのアグリゲート。
* 500GiBのプロビジョニング済み容量のPremium SSD v2マネージドディスク、ルートディスクとデータディスク。
* データStorage VMを1台導入し、NFS、CIFS、iSCSI、NVMe/TCPデータサービスを利用追加データStorage VMは追加できません。
* NFS、CIFS（SMB）、iSCSI、Autonomous Ransomware Protection（ARP）、SnapLock、SnapMirror用のライセンスがインストールされている。
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["ONTAPの温度依存型Storage Efficiency（TSSE）"^]、ボリューム暗号化、および外部キー管理がデフォルトで有効になっています。
* 次の機能はサポートされていません。
+
** FabricPool による階層化
** Storage VMタイプの変更
** 高速書き込みモード




.作業を開始する前に
* Azure Marketplaceの有効なサブスクリプションを所有していることを確認します。
* Azure内ののネットワーク要件を満たしていることを確認しますlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["単一のAZにHAを導入"]。を参照してください link:reference-networking-azure.html["Cloud Volumes ONTAP用のAzureネットワークのセットアップ"]。
* Cloud Volumes ONTAPを導入するには、次のAzureロールのいずれかが割り当てられている必要があります。
+
**  `contributor`デフォルトの権限を持つロール。詳細については、を参照して https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Azureのドキュメント：Azureの組み込みロール"^]ください。
** 次の権限を持つカスタムRBACロール。詳細については、を参照して https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Azureのドキュメント：Azureのカスタムロール"^]ください。
+
[]
====
"permissions"：[｛"actions"：["Microsoft.aad/register/action"、"Microsoft.Resources/subscriptions/resourceGroups/write"、"Microsoft.Network/loadBalancers/write" Microsoft.Compute/capacityReservationGroups/deploy/action" Microsoft.Compute/virtualMachines/write" Microsoft.Network/virtualNetworks/read" Microsoft.Compute/disks/write" Microsoft.Network/virtualNetworks/subnets/write"、"Microsoft.ClassicCompute/virtualMachines/networkInterfaces/networkSecurityResources/write" Microsoft.Network/networkInterfaces/write"、"Microsoft.DataGroups/write" Microsoft.Compute/virtualMachines/extensions/write"、",",",",",",",",",",",",",",",",",",",",",",",",",",",",". Microsoft.Network/virtualNetworks/write" Microsoft.Network/networkSecurityGroups/write" Microsoft.Network/networkSecurityGroups/read" Microsoft.Compute/virtualMachineScaleSets/write" Microsoft.Network/virtualNetworks/subnets/read"

====
+

NOTE: リソースプロバイダ「Microsoft.storage」をサブスクリプションに登録している場合は、権限は必要ありません `Microsoft.AAD/register/action`。詳細については、を参照して https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Azureのドキュメント：Azure Permissions for Storage"^]ください。





.手順
. Azure MarketplaceサイトでNetApp製品を検索します。
. NetApp Cloud Volumes ONTAP DIRECT *を選択します。
. [作成]*をクリックして導入ウィザードを起動します。
. 計画を選択します。通常、*プラン*リストにはCloud Volumes ONTAPの最新リリースが表示されます。
. [基本設定]タブで、次の詳細を指定します。
+
** *サブスクリプション*:サブスクリプションを選択します。展開はサブスクリプション番号にリンクされます。
** *リソースグループ*：既存のリソースグループを使用するか、新しいリソースグループを作成します。リソースグループを使用すると、Cloud Volumes ONTAPシステムの1つのグループ内でディスクやStorage VMなどのすべてのリソースを割り当てることができます。
** *リージョン*：単一のAZでAzure HAの導入をサポートするリージョンを選択します。リストには、使用可能なリージョンのみが表示されます。
** *サイズ*：サポートされているPremium SSD v2管理ディスク用のStorage VMサイズを選択します。
** *ゾーン*:選択したリージョンのゾーンを選択します。
** *管理者パスワード*：パスワードを設定します。導入後にこの管理者パスワードを使用してシステムにログインします。
** *パスワードの確認*：確認のために同じパスワードを再入力します。
+
*** [ネットワーク]*タブで、仮想ネットワークとサブネットを追加するか、リストから選択します。
+

NOTE: Microsoft Azureの制限事項に準拠するには、新しい仮想ネットワークのセットアップ時に新しいサブネットを作成する必要があります。同様に、既存のネットワークを選択する場合は、既存のサブネットを選択する必要があります。

*** 事前定義されたネットワークセキュリティグループを選択するには、* Yes *を選択します。事前定義されたAzureネットワークセキュリティグループに必要なトラフィックルールを割り当てるには、*[いいえ]*を選択します。詳細については、を参照してください link:reference-networking-azure.html#security-group-rules["Azure のセキュリティグループルール"]。
*** [Advanced]*タブで、この導入に必要な2つのAzure機能が設定されているかどうかを確認します。link:task-saz-feature.html["Cloud Volumes ONTAPの単一AZ環境でAzureの機能を有効にする"]およびを参照してくださいlink:task-azure-high-availability-mode.html["AzureでCloud Volumes ONTAPのハイアベイラビリティモードを有効にする"]。
*** [タグ]タブでは、リソースまたはリソースグループの名前と値のペアを定義できます。
*** [Review + Create]タブで、詳細を確認して導入を開始します。






.完了後
通知アイコンを選択すると、導入の進行状況が表示されます。Cloud Volumes ONTAPを導入したら、リストに処理用のStorage VMを表示できます。

アクセス可能になったら、ONTAP System ManagerまたはONTAP CLIを使用して、設定した管理者クレデンシャルでStorage VMにログインします。その後、ボリューム、LUN、または共有を作成して、Cloud Volumes ONTAPのストレージ機能の利用を開始できます。



== 導入に関する問題のトラブルシューティング

Azure Marketplaceから直接導入されたCloud Volumes ONTAPシステムには、NetAppによるサポートは含まれていません。導入時に問題が発生した場合は、個別にトラブルシューティングして解決できます。

.手順
. Azure Marketplaceサイトで、*[Boot diagnostics]>[Serial log]*に移動します。
. シリアルログをダウンロードして調査します。
. トラブルシューティングについては、製品マニュアルとナレッジベース（KB）記事を参照してください。
+
** https://learn.microsoft.com/en-us/partner-center/["Azure Marketplaceのドキュメント"]
** https://www.netapp.com/support-and-training/documentation/["NetApp のドキュメント"]
** https://kb.netapp.com/["NetAppの技術情報アーティクル"]






== BlueXP  で導入されたシステムを検出する

Azure Marketplaceの直接導入を使用して導入したCloud Volumes ONTAPシステムを検出し、BlueXP  で作業環境として管理できます。BlueXP  Connectorは、システムを検出して作業環境として追加し、必要なBlueXP  ライセンスを適用して、それらのシステムに対するBlueXP  のすべての機能をロック解除します。PSSD v2管理ディスクを使用する単一のAZ内の元のHA構成は保持され、システムは元の導入環境と同じAzureサブスクリプションとリソースグループに登録されます。

.このタスクについて
Azure Marketplaceの直接導入を使用して導入されたCloud Volumes ONTAPシステムを検出すると、BlueXP  Connectorは次のタスクを実行します。

* 検出されたシステムの空きライセンスを通常の容量ベースとして置き換えますlink:concept-licensing.html#packages["フリーミアムライセンス"]。
* 導入したシステムの既存の機能を維持し、データ保護、データ管理、セキュリティ機能など、BlueXP  の機能を追加します。
* ノードにインストールされているライセンスを、NFS、CIFS（SMB）、iSCSI、ARP、SnapLock、SnapMirrorの新しいONTAPライセンスに置き換えます。
* 汎用ノードのシリアル番号を一意のシリアル番号に変換します。
* 必要に応じて、リソースに新しいシステムタグを割り当てます。
* インスタンスの動的IPアドレスを静的IPアドレスに変換します。
* 導入したシステムでlink:task-tiering.html["FabricPool による階層化"]、、link:task-verify-autosupport.html["AutoSupport"]およびlink:concept-worm.html["Write-Once-Read-Many"]（WORM）ストレージの機能を有効にします。これらの機能は、必要に応じてBlueXP  コンソールからアクティブ化できます。
* インスタンスを検出するために使用されるNSSアカウントに登録します。
* 検出されたシステムに対しての容量管理機能を有効にしますlink:concept-storage-management.html#capacity-management["自動モードと手動モード"]。


.作業を開始する前に
Azure Marketplaceでの導入が完了していることを確認BlueXP  Connectorでシステムを検出できるのは、導入が完了して検出可能になった場合のみです。

.手順
BlueXP  では、既存のシステムを検出するための標準の手順に従います。を参照してください link:task-adding-systems.html["既存のCloud Volumes ONTAPシステムをBlueXP  に追加する"]。

.完了後
検出が完了すると、BlueXP  で作業環境として表示されたシステムを確認できます。link:task-manage-aggregates.html["アグリゲートの拡張"]、link:task-create-volumes.html["ボリュームの追加"]、、などのさまざまな管理タスクを実行できますlink:task-managing-svms-azure.html["追加のStorage VMのプロビジョニング"] link:task-change-azure-vm.html["インスタンスタイプの変更"]。

.関連リンク
ストレージの作成の詳細については、ONTAPのドキュメントを参照してください。

* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["NFS用のボリュームの作成"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["iSCSI用のLUNの作成"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["CIFS用の共有の作成"^]

