---
sidebar: sidebar 
permalink: task-accelerate-data-access.html 
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: FlexCache ボリュームは、元のボリュームまたはソースボリュームから NFS 読み取りデータをキャッシュするストレージボリュームです。その後キャッシュされたデータを読み取ることで、そのデータへのアクセスが高速になります。 
---
= FlexCache ボリュームでデータアクセスを高速化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FlexCache ボリュームは、元の（またはソース）ボリュームから NFS 読み取りデータをキャッシュするストレージボリュームです。その後キャッシュされたデータを読み取ることで、そのデータへのアクセスが高速になります。

FlexCache を使用すると、データアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィック負荷を軽減したりできます。FlexCache ボリュームを使用すると、元のボリュームにアクセスせずに直接データを使用できるため、特にクライアントが同じデータに繰り返しアクセスする場合に、パフォーマンスの向上に役立ちます。FlexCache ボリュームは、読み取り処理が大量に発生するシステムワークロードに適しています。

現時点ではFlexCache ボリュームの管理は提供されていませんが、ONTAP CLIまたはONTAP System Managerを使用してFlexCache ボリュームを作成および管理できます。

* http://["『 FlexCache Volumes for Faster Data Access Power Guide 』を参照してください"^]
* http://["System Manager での FlexCache ボリュームの作成"^]


3.7.2リリース以降、すべての新しいCloud Volumes ONTAP システム用のFlexCache ライセンスがBlueXPによって生成されます。ライセンスの使用量は 500GiB に制限されています。

video::PBNPVRUeT1o[youtube,width=848,height=480]