---
sidebar: sidebar 
permalink: task-managing-svms-azure.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported 
summary: Storage VM は ONTAP 内で実行される仮想マシンであり、クライアントにストレージサービスとデータサービスを提供します。これは SVM または SVM として認識されていることがあります。Cloud Volumes ONTAP にはデフォルトで 1 つの Storage VM が設定されますが、一部の設定では追加の Storage VM がサポートされます。 
---
= AzureのCloud Volumes ONTAP用のデータ提供用Storage VMを管理します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Storage VM は ONTAP 内で実行される仮想マシンであり、クライアントにストレージサービスとデータサービスを提供します。これは「_SVM_」や「_Vserver_」と呼ばれます。Cloud Volumes ONTAPにはデフォルトで1つのStorage VMが設定されますが、AzureでCloud Volumes ONTAPを実行する場合は追加でStorage VMを作成できます。

Azureで追加データサービスを提供するStorage VMを作成および管理するには、BlueXP  APIを使用する必要があります。これは、Storage VMの作成と必要なネットワークインターフェイスの設定のプロセスがAPIによって自動化されるためです。Storage VMを作成する際に、BlueXP  は必要なLIFサービスと、Storage VMからのアウトバウンドSMB / CIFS通信に必要なiSCSI LIFを設定します。



== サポートされている Storage VM 数

Cloud Volumes ONTAP 9.9.0以降では、ライセンスに基づいて、特定の構成で複数のStorage VMがサポートされます。使用しているCloud Volumes ONTAPのバージョンでサポートされるStorage VMの数を確認するには、を参照して https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html["Cloud Volumes ONTAP リリースノート"^]ください。

9.9.0より前のバージョンのCloud Volumes ONTAPでは、データ提供用Storage VMが1つとディザスタリカバリに使用されるデスティネーションStorage VMが1つずつサポートされます。ソース Storage VM で停止が発生した場合は、デスティネーション Storage VM をデータアクセス用にアクティブ化できます。

.作業を開始する前に
Cloud Volumes ONTAP用Storage VMを作成および管理するには、Connectorに特定の権限が必要です。必要な権限はに含まれてい https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["ネットアップが提供するポリシー"^]ます。



== Storage VM を作成

構成とライセンスタイプに応じて、BlueXP  APIを使用して、シングルノードシステムまたはハイアベイラビリティ（HA）構成で複数のStorage VMを作成できます。

.このタスクについて
APIを使用してStorage VMを作成し、必要なネットワークインターフェイスを設定すると、BlueXP  はNASデータLIFから次のサービスを削除し、アウトバウンド管理接続に使用するiSCSIデータLIFに追加することで、データStorage VMのポリシーも変更し `default-data-files`ます。

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`




=== シングルノードシステム

次のAPI呼び出しを使用して、シングルノードシステムにStorage VMを作成します。

`POST /azure/vsa/working-environments/{workingEnvironmentId}/svm`

要求の本文には次の情報が含まれている必要があります

[source, json]
----
{ "svmName": "myNewSvm1"
   "svmPassword": "optional, the API takes the cluster password if not provided"
   "mgmtLif": "optional, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== HA ペア

次のAPI呼び出しを使用して、Azure HA構成でStorage VMを作成します。

`POST /azure/ha/working-environments/{workingEnvironmentId}/svm`

要求の本文には次の情報が含まれている必要があります

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


== シングルノードシステムおよびHAペアのStorage VMを管理します。

BlueXP  APIを使用すると、シングルノード構成とHA構成の両方で、Storage VMの名前変更と削除を行うことができます。



=== Storage VMの名前を変更します

Storage VMの名前を変更するには、既存のStorage VMと新しいStorage VMの名前をパラメータとして指定する必要があります。

.手順
* 次のAPI呼び出しを使用して、シングルノードシステムでStorage VMの名前を変更します。
+
`PUT /azure/vsa/working-environments/{workingEnvironmentId}/svm`

+
要求の本文には次の情報が含まれている必要があります

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* HA構成のStorage VMの名前を変更するには、次のAPI呼び出しを使用します。
+
`PUT /azure/ha/working-environments/{workingEnvironmentId}/svm`

+
要求の本文には次の情報が含まれている必要があります

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== Storage VMを削除します

シングルノード構成またはHA構成では、アクティブなボリュームがないStorage VMを削除できます。

.手順
* 次のAPI呼び出しを使用して、シングルノードシステムのStorage VMを削除します。
+
`DELETE /azure/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* 次のAPI呼び出しを使用して、HA構成のStorage VMを削除します。
+
`DELETE /azure/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`


