---
sidebar: sidebar 
permalink: task-accelerate-data-access.html 
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: FlexCache ボリュームは、元のボリュームまたはソースボリュームから NFS 読み取りデータをキャッシュするストレージボリュームです。その後キャッシュされたデータを読み取ることで、そのデータへのアクセスが高速になります。 
---
= FlexCache ボリュームでデータアクセスを高速化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FlexCacheボリュームは、元の（ソース）ボリュームのSMBおよびNFS読み取りデータをキャッシュするストレージボリュームです。その後キャッシュされたデータを読み取ることで、そのデータへのアクセスが高速になります。

FlexCache を使用すると、データアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィック負荷を軽減したりできます。FlexCache ボリュームを使用すると、元のボリュームにアクセスせずに直接データを使用できるため、特にクライアントが同じデータに繰り返しアクセスする場合に、パフォーマンスの向上に役立ちます。FlexCache ボリュームは、読み取り処理が大量に発生するシステムワークロードに適しています。

BlueXPでは、FlexCacheボリュームを link:https://docs.netapp.com/us-en/bluexp-volume-caching/index.html["BlueXPのボリュームキャッシュ"^] サービス

ONTAP CLIまたはONTAPシステムマネージャを使用して、FlexCacheボリュームを作成および管理することもできます。

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["『 FlexCache Volumes for Faster Data Access Power Guide 』を参照してください"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["System Manager での FlexCache ボリュームの作成"^]


video::PBNPVRUeT1o[youtube,width=848,height=480]


== オリジンが暗号化されている場合のFlexCacheの操作

元のボリュームが暗号化されているCloud Volumes ONTAPシステムでFlexCacheを設定する場合は、FlexCacheボリュームが暗号化されたデータに適切にアクセスしてキャッシュできるように、追加の手順が必要です。

.作業を開始する前に
. *暗号化のセットアップ*：ソースボリュームが完全に暗号化され、動作可能であることを確認します。Cloud Volumes ONTAPシステムの場合、これにはクラウド固有のキー管理サービスとの統合が含まれます。


ifdef::aws[]

AWSの場合、これは通常、AWS Key Management Service（KMS）を使用することを意味します。詳細については、を参照して link:task-aws-key-management.html["AWS Key Management Serviceを使用してキーを管理します"]ください。

endif::aws[]

ifdef::azure[]

Azureの場合は、NetApp Volume Encryption（NVE）用のAzureキーヴォールトをセットアップする必要があります。詳細については、を参照して link:task-azure-key-vault.html["Azure Key Vaultを使用してキーを管理します"]ください。

endif::azure[]

ifdef::gcp[]

Google Cloudの場合は、Google Cloud Key Management Serviceです。詳細については、を参照して link:task-google-key-manager.html["GoogleのCloud Key Management Serviceを使用したキーの管理"]ください。

endif::gcp[]

. *キー管理サービス*：FlexCacheボリュームを作成する前に、Cloud Volumes ONTAPシステムでキー管理サービスが正しく設定されていることを確認してください。この設定は、FlexCacheボリュームが元のボリュームのデータを復号化するために不可欠です。
. *ライセンス*:有効なFlexCacheライセンスがCloud Volumes ONTAPシステムで使用可能で有効になっていることを確認します。
. * ONTAPバージョン*：ONTAPバージョンのCloud Volumes ONTAPシステムが、暗号化されたボリュームを含むFlexCacheをサポートしていることを確認します。詳細については、最新または互換性マトリックスを参照して https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAPリリースノート"^] ください。
. *ネットワーク構成*：ネットワーク構成で、元のボリュームとFlexCacheボリューム間のシームレスな通信が可能であることを確認します。これには、クラウド環境での適切なルーティングとDNS解決が含まれます。


.手順
Cloud Volumes ONTAPシステムに、暗号化されたソースボリュームを使用してFlexCacheボリュームを作成します。詳細な手順とその他の考慮事項については、次のセクションを参照してください。

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["『 FlexCache Volumes for Faster Data Access Power Guide 』を参照してください"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["System Manager での FlexCache ボリュームの作成"^]

