---
sidebar: sidebar 
permalink: task-managing-svms-gcp.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported, create svm, create storage vm, create vserver 
summary: Storage VM は ONTAP 内で実行される仮想マシンであり、クライアントにストレージサービスとデータサービスを提供します。これは SVM または SVM として認識されていることがあります。Cloud Volumes ONTAP にはデフォルトで 1 つの Storage VM が設定されますが、一部の設定では追加の Storage VM がサポートされます。 
---
= Google CloudでCloud Volumes ONTAP用のデータ提供用Storage VMを管理します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Storage VM は ONTAP 内で実行される仮想マシンであり、クライアントにストレージサービスとデータサービスを提供します。これは、 _ SVM _ または _ SVM _ であることがわかります。Cloud Volumes ONTAP にはデフォルトで 1 つの Storage VM が設定されますが、一部の設定では追加の Storage VM がサポートされます。

Google Cloudで追加データサービスを提供するStorage VMを作成および管理するには、BlueXP  APIを使用する必要があります。これは、Storage VMの作成と必要なネットワークインターフェイスの設定のプロセスがAPIによって自動化されるためです。Storage VMを作成する際に、BlueXP  は必要なLIFサービスと、Storage VMからのアウトバウンドSMB / CIFS通信に必要なiSCSI LIFを設定します。

Cloud Volumes ONTAP API呼び出しの実行については、を参照してください https://docs.netapp.com/us-en/bluexp-automation/cm/your_api_call.html#step-1-select-the-identifie["最初のAPI呼び出し"^]。



== サポートされている Storage VM 数

Cloud Volumes ONTAP 9.11.1以降では、ライセンスに基づいて、特定の構成で複数のStorage VMがサポートされます。使用しているCloud Volumes ONTAPのバージョンでサポートされるStorage VMの数を確認するには、を参照して https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Cloud Volumes ONTAP リリースノート"^]ください。

9.11.1より前のバージョンのCloud Volumes ONTAPでは、データ提供用Storage VMが1つとディザスタリカバリに使用されるデスティネーションStorage VMが1つずつサポートされます。ソース Storage VM で停止が発生した場合は、デスティネーション Storage VM をデータアクセス用にアクティブ化できます。



== Storage VM を作成

構成とライセンスタイプに応じて、BlueXP  APIを使用して、シングルノードシステムまたはハイアベイラビリティ（HA）構成で複数のStorage VMを作成できます。

.このタスクについて
APIを使用してStorage VMを作成し、必要なネットワークインターフェイスを設定すると、BlueXP  はNASデータLIFから次のサービスを削除し、アウトバウンド管理接続に使用するiSCSIデータLIFに追加することで、データStorage VMのポリシーも変更し `default-data-files`ます。

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.作業を開始する前に
Cloud Volumes ONTAP HAペア用のStorage VMを作成するには、コネクタに特定の権限が必要です。必要な権限はに含まれてい https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["ネットアップが提供するポリシー"^]ます。



=== シングルノードシステム

次のAPI呼び出しを使用して、シングルノードシステムにStorage VMを作成します。

`POST /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

要求の本文には次のパラメータを含めます。

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== HA ペア

次のAPI呼び出しを使用して、HAペアにStorage VMを作成します。

`POST /gcp/ha/working-environments/{workingEnvironmentId}/svm/`

要求の本文には次のパラメータを含めます。

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
}
----


== Storage VM を管理します

BlueXP  APIを使用すると、シングルノード構成とHA構成の両方で、Storage VMの名前変更と削除を行うことができます。

.作業を開始する前に
Cloud Volumes ONTAP HAペアのStorage VMを管理するには、コネクタに特定の権限が必要です。必要な権限はに含まれてい https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["ネットアップが提供するポリシー"^]ます。



=== Storage VMの名前を変更します

Storage VMの名前を変更するには、既存のStorage VMと新しいStorage VMの名前をパラメータとして指定する必要があります。

.手順
* 次のAPI呼び出しを使用して、シングルノードシステムでStorage VMの名前を変更します。
+
`PUT /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

+
要求の本文には次のパラメータを含めます。

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* HAペアのStorage VMの名前を変更するには、次のAPI呼び出しを使用します。
+
`PUT /gcp/ha/working-environments/{workingEnvironmentId}/svm`

+
要求の本文には次のパラメータを含めます。

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== Storage VMを削除します

シングルノード構成またはHA構成では、アクティブなボリュームがないStorage VMを削除できます。

.手順
* 次のAPI呼び出しを使用して、シングルノードシステムのStorage VMを削除します。
+
`DELETE /gcp/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* HAペアのStorage VMを削除するには、次のAPI呼び出しを使用します。
+
`DELETE /gcp/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`



.関連情報
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["API を使用する準備をします"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Cloud Volumes ONTAPワークフロー"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["必要な識別子を取得する"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["BlueXP REST APIを使用する"^]

