---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, bluexp license conversion for node based 
summary: ノードベースライセンスの販売終了（EOA）が完了したら、BlueXP  ライセンス変換ツールを使用して容量ベースのライセンスに移行する必要があります。 
---
= Cloud Volumes ONTAPノードベースライセンスを容量ベースライセンスに変換する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノードベースライセンスの販売終了（EOA）が完了したら、BlueXP  ライセンス変換ツールを使用して容量ベースのライセンスに移行する必要があります。

年間契約または長期契約の場合は、NetApp EOA日（2024年11月11日）またはライセンスの有効期限前にNetApp担当者に連絡して、移行の前提条件が満たされていることを確認することを推奨します。Cloud Volumes ONTAPノードの長期契約を結んでおらず、オンデマンドの従量課金制（PAYGO）サブスクリプションに対してシステムを運用している場合は、2024年12月31日のサポート終了（EOS）までに変換を計画することが重要です。どちらの場合も、BlueXP  ライセンス変換ツールを使用してシームレスに移行する前に、システムが要件を満たしていることを確認する必要があります。

EOAとEOSの詳細については、を参照してくださいlink:concept-licensing.html#end-of-availability-of-node-based-licenses["ノードベースライセンスの販売終了"]。

.このタスクについて
* ライセンス変換ツールを使用すると、ノードベースのライセンスモデルから容量ベースのライセンスモデルに移行できるため、データを移行したり、追加のクラウドリソースをプロビジョニングしたりする必要がありません。
* この処理は無停止で実行され、サービスの停止やアプリケーションのダウンタイムは発生しません。
* Cloud Volumes ONTAPシステムのアカウントデータとアプリケーションデータはそのまま維持されます。
* 基盤となるクラウドリソースは、変換後も影響を受けません。
* ライセンス変換ツールは、シングルノード、単一アベイラビリティゾーン（AZ）における高可用性（HA）、複数のAZにおけるHA、お客様所有のライセンスを使用（BYOL）、PAYGOなど、すべての導入タイプをサポートします。
* このツールは、すべてのノードベースライセンスをソースとして、すべての容量ベースライセンスをターゲットとしてサポートしています。例えば、PAYGO Standardのノードベースライセンスをお持ちの場合、マーケットプレイスで購入した任意の容量ベースライセンスに変換できます。NetAppはBYOLライセンスの購入、延長、更新を制限しています。詳細については、以下をご覧ください。  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAPの BYOL ライセンスの利用制限"^] 。
* この変換は、AWS、Azure、Google Cloudのすべてのクラウドプロバイダでサポートされています。
* 変換後、ノードベースライセンスのシリアル番号が容量ベースの形式に置き換えられます。これは変換の一環として行われ、NetAppサポートサイト（NSS）のアカウントに反映されます。
* 容量ベースモデルに移行した場合、データは引き続きノードベースのライセンスと同じ場所に保持されます。このアプローチは、データ配置の中断を保証するものではなく、移行全体を通じてデータ主権の原則を支持します。


.始める前に
* 顧客アクセス権または管理者アクセス権を持つNSSアカウントが必要です。
* NSSアカウントがBlueXP  ユーザクレデンシャルで登録されている必要があります。
* 作業環境は、顧客アクセス権または管理者アクセス権を持つNSSアカウントにリンクされている必要があります。
* 有効な容量ベースライセンス（BYOLライセンスまたはマーケットプレイスのサブスクリプション）を用意しておく必要があります。
* 容量ベースのライセンスがBlueXP  アカウントで提供されている必要があります。このライセンスは、マーケットプレイスのサブスクリプション、またはBlueXP  デジタルウォレットのBYOL /プライベートオファーパッケージにすることができます。
* 宛先パッケージを選択する前に、次の条件を理解してください。
+
** アカウントに容量ベースのBYOLライセンスがある場合は、アカウントのBYOL容量ベースライセンスと一致するデスティネーションパッケージを選択する必要があります。
+
*** がデスティネーションパッケージとして選択されている場合、 `Professional`アカウントにはプロフェッショナルパッケージを含むBYOLライセンスが必要です。
*** がデスティネーションパッケージとして選択されている場合、 `Essentials`アカウントにはEssentialsパッケージのBYOLライセンスが必要です。
*** がデスティネーションパッケージとして選択されている場合 `Optimized`、アカウントには最適化パッケージのBYOLライセンスが必要です。


** デスティネーションパッケージがアカウントのBYOLライセンスと一致しない場合は、容量ベースライセンスに選択したパッケージが含まれていない可能性があります。この場合、マーケットプレイスのサブスクリプションを通じて課金されます。
** 容量ベースのBYOLライセンスではなく、マーケットプレイスのサブスクリプションのみの場合、選択したパッケージが容量ベースのマーケットプレイスのサブスクリプションに含まれることを確認する必要があります。
** 既存の容量ベースライセンスに十分な容量がない場合や、追加の容量使用量に対して課金するMarketplaceのサブスクリプションをお持ちの場合は、Marketplaceのサブスクリプションを通じて追加の容量に対して課金されます。
** 既存の容量ベースライセンスに十分な容量がなく、使用容量の追加料金を請求するマーケットプレイスのサブスクリプションがない場合、変換は実行されません。容量の追加料金を請求するか、現在のライセンスに容量を拡張するには、Marketplaceのサブスクリプションを追加する必要があります。
** 移行先のパッケージがアカウントのBYOLライセンスの可用性と一致しない場合や、既存の容量ベースライセンスに十分な容量がない場合は、Marketplaceのサブスクリプションを通じて課金されます。





NOTE: これらの要件のいずれかが満たされていない場合、ライセンス変換は行われません。場合によっては、ライセンスが変換されても使用できないことがあります。情報アイコンをクリックして問題を特定し、対処方法を実行します。

.手順
. [Canvas]ページで、ライセンスタイプを変更する作業環境の名前をダブルクリックします。
. [Overview]タブで、[Features]パネルをクリックします。
. *充電方法*の横にある鉛筆アイコンを確認します。システムの充電方法がの場合は `Node Based`、容量別充電に変換できます。
+

TIP: Cloud Volumes ONTAPシステムがすでに容量単位で課金されている場合、またはいずれかの要件が満たされていない場合、アイコンは無効になります。

. [Convert Node-based licenses to Capacity-based]*画面で、作業環境名とソースライセンスの詳細を確認します。
. 既存のライセンスを変換するデスティネーションパッケージを選択してください：
+
** エッセンシャル。デフォルト値はです `Essentials`。
** プロフェッショナル




ifdef::azure[]

* 最適化（Azure向け）


endif::azure[]

ifdef::gcp[]

* 最適化（Google Cloud向け）


endif::gcp[]

. BYOLライセンスをお持ちの場合は、チェックボックスをオンにして、変換後にBlueXP  デジタルウォレットからノードベースのライセンスを削除できます。変換が完了していない場合は、このチェックボックスをオンにしても、ライセンスはデジタルウォレットから削除されません。Marketplaceサブスクリプションをお持ちの場合、このオプションは利用できません。
. チェックボックスを選択して、変更の影響を理解したことを確認し、*[続行]*をクリックします。


.完了後
新しいライセンスシリアル番号を表示し、BlueXP  デジタルウォレットの変更を確認します。
