---
sidebar: sidebar 
permalink: task-azure-high-availability-mode.html 
keywords: high availability mode, EnableHighAvailabilityMode, action required, nfsv4 
summary: 計画外フェイルオーバーの時間を短縮し、NFSv4でCloud Volumes ONTAPをサポートするには、Microsoft Azureのハイアベイラビリティモードを有効にする必要があります。 
---
= Azureでハイアベイラビリティモードを有効にする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
計画外フェイルオーバーの時間を短縮し、NFSv4でCloud Volumes ONTAPをサポートするには、Microsoft Azureのハイアベイラビリティ（HA）モードを有効にする必要があります。このモードでは、Cloud Volumes ONTAP HAノードは、CIFSクライアントおよびNFSv4クライアントでの計画外フェイルオーバー時に短い（60秒）目標復旧時間（RTO）を達成できます。

Cloud Volumes ONTAP 9.10.1以降では、Microsoft Azureで実行されるCloud Volumes ONTAP HAペアの計画外フェイルオーバーにかかる時間が短縮され、NFSv4のサポートが追加されました。これらの機能拡張をCloud Volumes ONTAPで利用できるようにするには、Azureサブスクリプションで高可用性機能を有効にする必要があります。

Azureサブスクリプションでこの機能を有効にする必要がある場合、「Action Required」メッセージにこれらの詳細が表示されます。

次の点に注意してください。

* Cloud Volumes ONTAP HA ペアの高可用性に問題はありません。この Azure 機能は、 ONTAP と連携して動作し、計画外のフェイルオーバーによって発生する NFS プロトコルのアプリケーション停止時間を短縮します。
* この機能を有効にしても、 Cloud Volumes ONTAP HA ペアの処理は中断されません。
* Azureサブスクリプションでこの機能を有効にしても、他のVMで問題が発生することはありません。
* Cloud Volumes ONTAPは、CIFSクライアントおよびNFSクライアントでのクラスタおよびSVM管理LIFのフェイルオーバー時に、内部のAzureロードバランサを使用します。
* HAモードを有効にすると、BlueXP  は12時間ごとにシステムをスキャンして内部のAzureロードバランサルールを更新します。


「Owner」権限があるAzureユーザは、Azure CLIからこの機能を有効にできます。

.手順
. https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart["Azure PortalからAzure Cloud Shellにアクセスします"^]
. ハイアベイラビリティモード機能を登録します。
+
[source, azurecli]
----
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
----
. 必要に応じて、機能が登録されたことを確認します。
+
[source, azurecli]
----
az feature show --name EnableHighAvailabilityMode --namespace Microsoft.Network
----
+
Azure CLIから次のような結果が返されることを確認します。

+
[listing]
----
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Features/providers/Microsoft.Network/features/EnableHighAvailabilityMode",
  "name": "Microsoft.Network/EnableHighAvailabilityMode",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
----

